version: '3.8'

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      PORT: 5000
      DATABASE_URL: mysql://root:password@db:3306/task_db
      JWT_SECRET: your_secret_key
    volumes:
      - .:/usr/src/app
    command: npm start

volumes:
  db_data:
